security:
  firewalls:
    main:
      pattern: ^/api
      anonymous: true
      lazy: true
      logout: ~

      guard:
        authenticators:
          - App\Security\TokenAuthenticator

      # disable storing the user in the session
      stateless: true
