security:
  access_control:
    - path: ^/admin$
      allow_if: "request.getClientIp() not in [127.0.0.1,::1]"
  firewalls:
    main:
      pattern: ^/store
      anonymous: true
      lazy: true
      logout: ~

      guard:
        authenticators:
          - App\Security\TokenAuthenticator

      # disable storing the user in the session
      stateless: true
